baseurl: https://randigrows.netlify.app/
title: Randi Grows
theme: hugo-creative-portfolio-theme
languageCode: en-us
disqusShortname: ''
googleAnalytics: ''
params:
  description: This is about my garden. 
  email: rbolt@pdx.edu
  navlinks:
    - home: yes
      name: About
      url: about/
    - name: General Garden 
      url: garden/
    - name: Cannabis
      url: weed/
    - name: Tomatoes
      url: tomatoes/
    - name: Broccoli
      url: broccoli/
    - name: Rosemary
      url: rosemary/
    - name: Get in touch
      url: contact/
  sidebarAbout:
    - This blog was created the summer of 2021 to track my findings and the progress of plants in my garden. This blog was created in R Studio using blogdown.    
    - Portland, Oregon.
social:
  email: rbolt@pdx.edu
  github: https://github.com/rbolt13
style: default